#!/usr/bin/env bash
# =============================================================================
# ProcedureGuard - Azure provisioning (Layer 1 infra + Layer 2 services)
# Creates: Resource Group, Storage (Layer 1/4), AI Search (Layer 2 retrieval),
#          Azure OpenAI (gpt-4o verbalization+reasoning, text-embedding-3-large),
#          Azure AI multi-service account (Vision multimodal embeddings + Doc Intelligence)
# Writes all endpoints + keys to ../.env
# =============================================================================
set -euo pipefail

# ----------------------------- EDIT THESE ------------------------------------
SUFFIX="$(date +%s | tail -c 5)"          # keeps names globally unique
LOCATION="centralindia"                          # pick a region with gpt-4o + Vision mm-embeddings
RG="rg-procedureguard"
STORAGE="stpguard${SUFFIX}"                # 3-24 chars, lowercase+digits only
CONTAINER="sop-docs"
SEARCH="srch-pguard-${SUFFIX}"
AOAI="aoai-pguard-${SUFFIX}"
MULTI="cog-pguard-${SUFFIX}"               # multi-service: Vision + Doc Intelligence
SEARCH_SKU="basic"
AOAI_LOCATION="swedencentral"
# -----------------------------------------------------------------------------

echo ">> Using subscription: $(az account show --query name -o tsv)"
echo ">> Resource group: $RG  Region: $LOCATION"

az group create --name "$RG" --location "$LOCATION" -o none
echo "[ok] resource group"

# ---- Storage (Layer 1 input archive + Layer 4 blob) -------------------------
az storage account create --name "$STORAGE" --resource-group "$RG" \
  --location "$LOCATION" --sku Standard_LRS --kind StorageV2 -o none
STORAGE_KEY="$(az storage account keys list -g "$RG" -n "$STORAGE" --query '[0].value' -o tsv)"
az storage container create --name "$CONTAINER" --account-name "$STORAGE" \
  --account-key "$STORAGE_KEY" -o none
STORAGE_CONN="$(az storage account show-connection-string -g "$RG" -n "$STORAGE" -o tsv)"
echo "[ok] storage + container '$CONTAINER'"

# ---- Azure AI Search (Layer 2 retrieval engine) -----------------------------
az search service create --name "$SEARCH" --resource-group "$RG" \
  --location "$LOCATION" --sku "$SEARCH_SKU" --partition-count 1 --replica-count 1 -o none
SEARCH_KEY="$(az search admin-key show -g "$RG" --service-name "$SEARCH" --query primaryKey -o tsv)"
SEARCH_ENDPOINT="https://${SEARCH}.search.windows.net"
echo "[ok] AI Search: $SEARCH_ENDPOINT"

# ---- Azure OpenAI (verbalization + embeddings + reasoning) ------------------
az cognitiveservices account create --name "$AOAI" --resource-group "$RG" \
  --location "$AOAI_LOCATION" --kind OpenAI --sku S0 --custom-domain "$AOAI" -o none
AOAI_ENDPOINT="$(az cognitiveservices account show -g "$RG" -n "$AOAI" --query properties.endpoint -o tsv)"
AOAI_KEY="$(az cognitiveservices account keys list -g "$RG" -n "$AOAI" --query key1 -o tsv)"

# gpt-4o for image verbalization (indexing) AND compliance reasoning (Agent 2)
az cognitiveservices account deployment create -g "$RG" -n "$AOAI" \
  --deployment-name gpt-4o --model-name gpt-4o --model-version "2024-08-06" \
  --model-format OpenAI --sku-capacity 20 --sku-name Standard -o none
# text-embedding-3-large for text vectors
az cognitiveservices account deployment create -g "$RG" -n "$AOAI" \
  --deployment-name text-embedding-3-large --model-name text-embedding-3-large \
  --model-version "1" --model-format OpenAI --sku-capacity 50 --sku-name Standard -o none
echo "[ok] Azure OpenAI deployments: gpt-4o, text-embedding-3-large"

# ---- Multi-service account (Vision multimodal embeddings + Doc Intelligence) -
az cognitiveservices account create --name "$MULTI" --resource-group "$RG" \
  --location "$LOCATION" --kind CognitiveServices --sku S0 --custom-domain "$MULTI" -o none
MULTI_ENDPOINT="$(az cognitiveservices account show -g "$RG" -n "$MULTI" --query properties.endpoint -o tsv)"
MULTI_KEY="$(az cognitiveservices account keys list -g "$RG" -n "$MULTI" --query key1 -o tsv)"
echo "[ok] multi-service (Vision mm-embeddings + Doc Intelligence)"

# ---- Write .env -------------------------------------------------------------
cat > ../.env <<EOF
# Generated by 00_provision_azure.sh on $(date -u)
AZ_RESOURCE_GROUP=$RG
AZ_LOCATION=$LOCATION

# Layer 1 / 4 - Blob Storage
STORAGE_ACCOUNT=$STORAGE
STORAGE_CONTAINER=$CONTAINER
STORAGE_KEY=$STORAGE_KEY
STORAGE_CONNECTION_STRING=$STORAGE_CONN

# Layer 2 - AI Search
SEARCH_ENDPOINT=$SEARCH_ENDPOINT
SEARCH_ADMIN_KEY=$SEARCH_KEY
SEARCH_INDEX_NAME=procedureguard-sop-index
SEARCH_API_VERSION=2025-08-01-preview

# Azure OpenAI
AOAI_ENDPOINT=$AOAI_ENDPOINT
AOAI_KEY=$AOAI_KEY
AOAI_GPT4O_DEPLOYMENT=gpt-4o
AOAI_EMBED_DEPLOYMENT=text-embedding-3-large

# Multi-service (Vision multimodal embeddings + Document Intelligence)
COG_ENDPOINT=$MULTI_ENDPOINT
COG_KEY=$MULTI_KEY
EOF

echo ""
echo "============================================================"
echo " DONE. Wrote ../.env"
echo " Load it before running the Python scripts:"
echo "     set -a && source .env && set +a"
echo "============================================================"
